package roomescape.global;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseInitialization {
	private final JdbcTemplate jdbcTemplate;
	
	@Autowired
	public DatabaseInitialization(JdbcTemplate jdbcTemplate) {
		this.jdbcTemplate = jdbcTemplate;
	}
	
	public void initializeTables() {
		initializeReservationTable();
	}
	
	private void initializeReservationTable() {
		jdbcTemplate.execute("DROP TABLE IF EXISTS reservations CASCADE");
		
		jdbcTemplate.execute("""
				CREATE TABLE reservations (
					id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					name VARCHAR(32),
					time TIMESTAMP)
				""");
		
		jdbcTemplate.execute("CREATE INDEX by_time ON reservations (time)");
	}
}
